version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - "8080:8080"
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"

volumes:
    jenkins_data:
      driver: local
    nexus_data:
      driver: local
